pipeline:
  name: cafe
  identifier: cafe
  projectIdentifier: Sarthak
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: asc
        identifier: asc
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: efw
                  identifier: efw
                  type: HarnessApproval
                  timeout: 2d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - _project_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
