pipeline:
  name: Connector
  identifier: Connector
  tags: {}
  projectIdentifier: doNotDeleteSarthakTest
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: s1
                  identifier: s1
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account.NGPipeAutoSlackNotifylgkBMYgVUv
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: s2
        identifier: s2
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.K8sConnector04Oi8P9LBP
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: org.CDCNGAuto_OrgLevelAzureConnector5Hc
                    image: <+input>
                    shell: Sh
                    command: echo 1
                  description: s1
  properties:
    ci:
      codebase:
        connectorRef: SarthakGithub
        build: <+input>
