pipeline:
  name: main-test
  identifier: maintest
  tags: {}
  template:
    templateRef: mian123456
    versionLabel: v1
    gitBranch: main
    templateInputs:
      stages:
        - stage:
            identifier: s1
            template:
              templateInputs:
                type: Deployment
                spec:
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
  projectIdentifier: Sarthak
  orgIdentifier: default
